
# function-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: function-secrets
type: Opaque
data:
  AzureWebJobsStorage: RGVmYXVsdEVuZHBvaW50c1Byb3RvY29sPWh0dHBzO0FjY291bnROYW1lPWNsYW1hdmFhenVyZWZ1bmN0aW9udGVzdDtBY2NvdW50S2V5PU1jaS9hc3Z6MUR0QXpMZVl6V0w0KytZMndhL3gvWmVkS1RzaVArYXBVWEJaWXRseS91K210UU41blNyUlJ6dnYyK1JmMWo1aTVobFkrQVN0Z20wbmZ3PT07RW5kcG9pbnRTdWZmaXg9Y29yZS53aW5kb3dzLm5ldA==
