
# function-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: function-secrets
type: Opaque
data:
  AzureWebJobsStorage: <your base64 storage account connection string>       ###Get your azure storage account string and then convert it to base-64
