name: Docker Build and Push to GHCR

on:
  push:
    branches:
      - main  # or any other branch you want to trigger your workflow
    paths:
      - 'BlobScanFunctionApp/**'  # This ensures the workflow only runs if there are changes in the specified path

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}  # Make sure to set CR_PAT in your repository secrets

    - name: Build the Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/my-app:${{ github.sha }} -f BlobScanFunctionApp/Dockerfile BlobScanFunctionApp/

    - name: Push the Docker image to GHCR
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/my-app:${{ github.sha }}

    # Any additional steps like deployment can be added here.
