name: Build and Push Function App

on:
  push:
    branches:
      - main
    paths:
      - 'BlobScanFunctionApp/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker build ./BlobScanFunctionApp -t ${{ secrets.DOCKER_USERNAME }}/functionapp:${{ github.sha }}

      - name: Push the Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/functionapp:${{ github.sha }}

