name: Scan Docker Image with Trivy

on:
  push:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Run Trivy vulnerability scanner on Docker Hub image
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'image'
        image-ref: 'ezio22/myazurefunctionapp:latest'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        severity: 'HIGH,CRITICAL'
        output: 'trivy-image-report.txt'

    - name: Upload Trivy scan results
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: trivy-report
        path: trivy-image-report.txt
