name: Build and Scan Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./BlobScanFunctionApp
          file: ./BlobScanFunctionApp/Dockerfile
          push: true
          tags: ezio22/azurfunctiontrivy:latest

      - name: Run Trivy vulnerability scanner on built image
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'image'
          image-ref: 'ezio22/azurfunctiontrivy:latestt'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'HIGH,CRITICAL'
          output: 'trivy-image-report.txt'

      - name: Upload Trivy scan report
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: trivy-image-report
          path: trivy-image-report.txt
