name: Docker CI

on:
  push:
    branches: [ main ]
    paths:
      - 'BlobScanFunctionApp/**'  # Trigger only when there are changes in the BlobScanFunctionApp directory

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to the GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }} # Ensure you have this secret set in your GitHub repo

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: BlobScanFunctionApp/
        file: BlobScanFunctionApp/Dockerfile
        push: true
        tags: ghcr.io/theslash84/my-app:e35cd78032e929c4b27ee79e6526d14b410a6976
