name: Trivy Repository Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  trivy-repo-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Run Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'table'
          output: 'trivy-report.txt'
          vuln-type: 'os,library'
          severity: 'HIGH,CRITICAL'
          path: '.'


      - name: Upload Trivy scan results
        uses: actions/upload-artifact@v2
        with:
          name: trivy-report
          path: trivy-report.txt

      - name: Display the scan results
        run: cat trivy-report.txt
