name: Trivy Vulnerability Scanner

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  trivy_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Build the Docker image
        run: |
          docker build -t myapp:latest .

      - name: Install Trivy
        run: |
          sudo apt-get install wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy

      - name: Scan the Docker image with Trivy
        run: |
          trivy image --exit-code 1 --no-progress --severity HIGH,CRITICAL myapp:latest

      # The following steps would typically include pushing the image to a registry,
      # deploying to a cluster, or other CI/CD steps. You'd only reach these steps
      # if the Trivy scan did not find any HIGH or CRITICAL vulnerabilities.
      - name: Log in to Docker Hub
        if: success()
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push the Docker image
        if: success()
        run: docker push myapp:latest
