name: Trivy Repository Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  trivy_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          input: './'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'HIGH,CRITICAL'

      - name: Run Trivy vulnerability scanner
        run: trivy fs --exit-code 1 --no-progress --severity HIGH,CRITICAL ./ > trivy-report.txt

      - name: Upload Trivy Scan Report
        uses: actions/upload-artifact@v2
        with:
          name: trivy-report
          path: trivy-report.txt
